[2022-05-14 12:08:59.659] [remoteagent] [info] Extension host agent started.
[2022-05-14 12:09:01.354] [remoteagent] [info] [127.0.0.1][2204dc44][ManagementConnection] New connection established.
[2022-05-14 12:09:01.863] [remoteagent] [info] [127.0.0.1][283040f7][ExtensionHostConnection] New connection established.
[2022-05-14 12:09:05.421] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-05-14 12:09:09.371] [remoteagent] [error] ptyHost was unable to resolve shell environment {}
[2022-05-14 12:09:09.372] [remoteagent] [error] RequestService#request (node) resolving shell environment failed {}
[2022-05-14 12:09:09.374] [remoteagent] [error] ExtensionHostConnection#buildUserEnvironment resolving shell environment failed {}
[2022-05-14 12:09:09.422] [remoteagent] [info] [127.0.0.1][283040f7][ExtensionHostConnection] <117> Launched Extension Host Process.
[2022-05-14 12:09:12.937] [remoteagent] [error] ExtensionHostConnection#buildUserEnvironment resolving shell environment failed {}
[2022-05-14 13:58:53.384] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/jtorne2)
[2022-05-14 13:58:53.397] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-05-14 15:45:32.747] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/jtorne2)
[2022-05-14 15:45:32.750] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
